Initial refactor to implement issue #2 (docksal_cli). For further implementation.

diff --git a/utils/kernel/core b/utils/kernel/core
--- a/utils/kernel/core
+++ b/utils/kernel/core
@@ -14,27 +14,40 @@ fi
 script_name=$1
 shift
 
+## Every util except "docktie_cli" needs a config...
 SCRIPT_CONF="$(dirname $0)/conf/${script_name}.conf"
-if [[ -e "$SCRIPT_CONF" ]]; then
-    . $SCRIPT_CONF
-else
-    echo "ERROR: Unconfigured util name ($script_name). See 'conf/artisan.conf' for reference in creating one."
-    echo
-    exit 1;
+if [[ "$script_name" != "docktie_cli" ]]; then
+    if [[ -e "$SCRIPT_CONF" ]]; then
+        . $SCRIPT_CONF
+    else
+        echo "ERROR: Unconfigured util name ($script_name). See 'conf/artisan.conf' for reference in creating one."
+        echo
+        exit 1;
+    fi
 fi
 
 ## ------
 ## main()
 ## ------
-if [[ "$script_name" = "composer" ]]; then
-   $DOCKER_COMPOSE_BIN run --rm $docker_service_name $*
-else
-   if [[ $# -eq 0 ]] && [[ "$script_name" != "shell" ]] ; then
-      echo "ERROR: parameter to '$script_name' missing."
-      echo
-      exit 1
-   else
-      DOCKER_CONTAINER="$DOCKER_COMPOSE_BIN exec $docker_service_name"
-      $DOCKER_CONTAINER $command_within_service $*
-   fi
-fi
+case $script_name in
+   "composer")
+       $DOCKER_COMPOSE_BIN run --rm $docker_service_name $*
+   ;;
+
+   "docktie_cli")
+       . $(dirname $0)/module/cli.inc
+       cli $*
+   ;;
+
+   *)
+       ## TODO: 'shell' will become a sub-command of `docktie_cli` later
+       if [[ $# -eq 0 ]] && [[ "$script_name" != "shell" ]] ; then
+          echo "ERROR: parameter to '$script_name' missing."
+          echo
+          exit 1
+       else
+          DOCKER_CONTAINER="$DOCKER_COMPOSE_BIN exec $docker_service_name"
+          $DOCKER_CONTAINER $command_within_service $*
+       fi
+   ;;
+esac
